version: '3.7'
services:
  db:
    image: postgres:14
    container_name: conexa_db
    env_file: .env
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    external: false
